add_newline = false
command_timeout = 2000
scan_timeout = 500
format = "$directory$git_branch$git_status$dotnet$character"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "git:"
format = "[$symbol$branch]($style)"

[git_status]
format = "[$all_status$ahead_behind]($style)"
ignore_submodules = true

[nodejs]
disabled = true
format = "[node $version]($style)"

[bun]
disabled = true

[python]
disabled = true
format = "[py $version]($style)"

[dotnet]
format = "[dotnet $version]($style)"
