add_newline = true
command_timeout = 2000
scan_timeout = 500
format = "$directory$git_branch$git_status$dotnet$character"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]

[git_status]
ignore_submodules = true

[nodejs]
disabled = true

[bun]
disabled = true

[python]
disabled = true

[dotnet]
format = "[$symbol$version]($style) "
symbol = ".NET "
